name: Script Github entrenamiento

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-python:
    runs-on: windows-latest

    steps:
    - name: Recopilar los datos del repositorio
      uses: actions/checkout@v4
    
    - name: Configurar entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Actualizar PIP
      run: python -m pip install --upgrade pip

    - name: Instalar dependencias desde requirements.txt
      run: python -m pip install -r requirements.txt

    - name: Listar entorno instalado (Verificación)
      run: python -m pip list

    - name: Ejecutar script de Python
      env:
        VALORANT_API_KEY: ${{ secrets.VALORANT_API_KEY }}
        PYTHONIOENCODING: utf-8
      run: |
        echo "=== INICIANDO EJECUCIÓN DEL SCRIPT ==="
        python script_entrenamiento.py
        echo "=== SCRIPT FINALIZADO ==="

    - name: Subir datos recopilados
      shell: bash
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
              
        git add -A
        
        echo "=== ESTADO DE GIT ANTES DEL COMMIT ==="
        git status
        
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto: Actualización de datos recopilados" && git push origin HEAD:${{ github.ref_name }})
